-- MySQL Script generated by MySQL Workbench
-- 03/26/16 23:33:36
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema forigi-cms
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema forigi-cms
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `forigi-cms` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `forigi-cms` ;

-- -----------------------------------------------------
-- Table `forigi-cms`.`topics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `forigi-cms`.`topics` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(66) NOT NULL,
  `caption` VARCHAR(50) NULL,
  `description` VARCHAR(1000) NULL,
  `img` VARCHAR(50) NULL,
  `add_date` DATETIME NOT NULL,
  `poster` VARCHAR(50) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `forigi-cms`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `forigi-cms`.`categories` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  `description` VARCHAR(1000) NULL,
  `parent_id` INT UNSIGNED NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `forigi-cms`.`videos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `forigi-cms`.`videos` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(50) NOT NULL,
  `url` VARCHAR(500) NOT NULL,
  `add_date` DATETIME NOT NULL,
  `topic_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_topic_id_idx` (`topic_id` ASC),
  CONSTRAINT `fk_topic_id_2`
    FOREIGN KEY (`topic_id`)
    REFERENCES `forigi-cms`.`topics` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `forigi-cms`.`images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `forigi-cms`.`images` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(50) NULL,
  `img` VARCHAR(50) NOT NULL,
  `add_date` DATETIME NOT NULL,
  `topic_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_topic_id_idx` (`topic_id` ASC),
  CONSTRAINT `fk_topic_id_3`
    FOREIGN KEY (`topic_id`)
    REFERENCES `forigi-cms`.`topics` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `forigi-cms`.`categories_to_topics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `forigi-cms`.`categories_to_topics` (
  `category_id` INT UNSIGNED NOT NULL,
  `topic_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`category_id`, `topic_id`),
  INDEX `fk_topic_id_idx` (`topic_id` ASC),
  CONSTRAINT `fk_category_id`
    FOREIGN KEY (`category_id`)
    REFERENCES `forigi-cms`.`categories` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_topic_id_1`
    FOREIGN KEY (`topic_id`)
    REFERENCES `forigi-cms`.`topics` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `forigi-cms`.`topics_translations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `forigi-cms`.`topics_translations` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(66) NOT NULL,
  `caption` VARCHAR(50) NULL,
  `description` VARCHAR(1000) NOT NULL,
  `lang` CHAR(2) NOT NULL DEFAULT 'en',
  `topic_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_topic_id_idx` (`topic_id` ASC),
  CONSTRAINT `fk_topic_id_4`
    FOREIGN KEY (`topic_id`)
    REFERENCES `forigi-cms`.`topics` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `forigi-cms`.`news`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `forigi-cms`.`news` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(66) NOT NULL,
  `text` VARCHAR(1000) NULL,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
